<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    
    <!-- App Information -->
    <AssemblyName>AKNOVABROW</AssemblyName>
    <RootNamespace>AKNOVABROW</RootNamespace>
    <AssemblyTitle>AKNOVA Browser</AssemblyTitle>
    <Product>AKNOVA Browser</Product>
    <Company>AKNOVA</Company>
    <Copyright>Copyright © 2025 AKNOVA. All rights reserved.</Copyright>
    <Version>1.0.1</Version>
    <FileVersion>1.0.1.0</FileVersion>
    
    <!-- Publishing Settings -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>false</PublishTrimmed>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2739.15" />
  </ItemGroup>

</Project>